# Use Debian as base image
FROM debian:bullseye

# Install packages
RUN apt-get update && apt-get install -y vsftpd openssl

# Create required folder
RUN mkdir -p /var/run/vsftpd/empty

# Copy configuration and entrypoint script
COPY conf/vsftpd.conf /etc/vsftpd.conf
COPY tools/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Set environment variable for username (optional)
ARG FTP_USER
ENV FTP_USER=${FTP_USER:-ftpuser}

# Expose ports for FTP and passive mode
EXPOSE 21 30000-30009

# Run entrypoint script
CMD ["/entrypoint.sh"]
