# Base image
FROM debian:bullseye

# Set working directory inside the container
WORKDIR /site

# Install system dependencies and Node.js
RUN apt-get update && \
    apt-get install -y curl gnupg && \
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copy all project files into the container
COPY ./site/ .

# Install project dependencies
RUN npm install && npm run build && npm install -g serve

# Expose the default Vite development server port
EXPOSE 5173

# Start the Vite development server
CMD ["serve", "-s", "dist", "-l", "5173"]