networks:
  app_net:

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - app_net
    volumes:
      - wordpress_data:/var/www/html
    restart: always

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    env_file:
      - .env
    environment:
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password.txt
      CREDENTIALS_FILE: /run/secrets/credentials.txt
    secrets:
      - db_password.txt
      - credentials.txt
    networks:
      - app_net
    volumes:
      - wordpress_data:/var/www/html
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password.txt
      MARIADB_PASSWORD_FILE: /run/secrets/db_password.txt
    secrets:
      - db_root_password.txt
      - db_password.txt
    networks:
      - app_net
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
  
  redis:
     container_name: redis
     build: ./requirements/bonus/redis
     networks:
        - app_net
     restart: always

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/sde-carv/data/wordpress
      o: bind

  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/sde-carv/data/mariadb
      o: bind

secrets:
  db_root_password.txt:
    file: ../secrets/db_root_password.txt
  db_password.txt:
    file: ../secrets/db_password.txt
  credentials.txt:
    file: ../secrets/credentials.txt